### ISSUE TITLE
panic when calling .all() on a parsed RRULE

### ISSUE THREAD

**Issue by aggregat4** [fmeringdal/rust_rrule#12]
When calling `.all()` on a ruleset in the following testcase: 

```
#[test]
    fn rrule_all_fails_with_panic() {
        "DTSTART;VALUE=DATE:20201230T130000\nRRULE:FREQ=MONTHLY;UNTIL=20210825T120000Z;INTERVAL=1;BYDAY=-1WE".parse::<RRuleSet>().unwrap().all();
    }
```

It fails with a panic:

```
called `Option::unwrap()` on a `None` value
thread 'meeters_ical::tests::rrule_all_fails_with_panic' panicked at 'called `Option::unwrap()` on a `None` value', /home/boris/.cargo/registry/src/github.com-1ecc6299db9ec823/rrule-0.3.8/src/iter/mod.rs:172:52
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/io/mod.rs:1537
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:176
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:214
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  12: rust_begin_unwind
             at src/libstd/panicking.rs:437
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  14: core::panicking::panic
             at src/libcore/panicking.rs:50
  15: core::option::Option<T>::unwrap
             at /home/boris/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/macros/mod.rs:10
  16: rrule::iter::increment_counter_date
             at /home/boris/.cargo/registry/src/github.com-1ecc6299db9ec823/rrule-0.3.8/src/iter/mod.rs:172
  17: rrule::iter::iter
             at /home/boris/.cargo/registry/src/github.com-1ecc6299db9ec823/rrule-0.3.8/src/iter/mod.rs:124
  18: rrule::rruleset_iter::RRuleSetIter::iter
             at /home/boris/.cargo/registry/src/github.com-1ecc6299db9ec823/rrule-0.3.8/src/rruleset_iter.rs:155
  19: rrule::rruleset::RRuleSet::all
             at /home/boris/.cargo/registry/src/github.com-1ecc6299db9ec823/rrule-0.3.8/src/rruleset.rs:49
  20: meeters::meeters_ical::tests::rrule_all_fails_with_panic
             at src/meeters_ical.rs:553
```

**Comment by fmeringdal** [comment]
Hi,
I found the bug, it tried to add a date that was invalid to result (28.02.2021).
This test is now passing in v.0.5.5. Let me know if you experience some other issues.

**Comment by aggregat4** [comment]
Wow, thank you for the super fast turnaround. Confirmed that this now works.
