### ISSUE TITLE
Recurrance evaulation with a specified timezone fails when moving past daylight savings

### ISSUE THREAD

**Issue by stevenallen05** [fmeringdal/rust_rrule#9]
I'm trying to get the local time for a recurring event that crosses the local DST changeover (on in 2021 is on March 14th for America/Vancouver), and I'm getting an  `invalid time` panic. I did some digging, and the panic is happeing specifically when trying to create the date for the occurance that happens on the DST changeover date:

```rust
    let rrule: RRule = "DTSTART;TZID=America/Vancouver:20210301T022210\nRRULE:FREQ=DAILY;COUNT=30".parse().unwrap();

    println!("Found occurances: {:?}",  rrule.all());
```

Backtrace:

```
thread 'main' panicked at 'invalid time', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/date.rs:83:42
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::option::expect_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1226
   3: core::option::Option<T>::expect
             at /home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:346
   4: chrono::date::Date<Tz>::and_hms
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/date.rs:83
   5: rrule::rrule_iter::generate
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/rrule-0.5.2/src/rrule_iter.rs:114
   6: <rrule::rrule_iter::RRuleIter as core::iter::traits::iterator::Iterator>::next
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/rrule-0.5.2/src/rrule_iter.rs:31
   7: alloc::vec::Vec<T>::extend_desugared
             at /home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:2431
   8: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend
             at /home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:2354
   9: <alloc::vec::Vec<T> as alloc::vec::SpecFromIterNested<T,I>>::from_iter
             at /home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:2139
  10: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
             at /home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:2162
  11: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:2002
  12: core::iter::traits::iterator::Iterator::collect
             at /home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1670
  13: rrule::rrule::RRule::all
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/rrule-0.5.2/src/rrule.rs:19
  14: rrule_test::main
             at ./src/main.rs:15
  15: core::ops::function::FnOnce::call_once
             at /home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Dependencies:

```toml

[dependencies]
chrono = "0.4.19"
chrono-tz = "0.5.3"
rrule = "0.5.2"
```

**Comment by stevenallen05** [comment]
And of course, I just figured out _why_ it was panicking. There _was_ no 2:22 AM that day in Vancouver due to the DST changeover 🤦 

Any suggestions on how to deal with this edge case?

**Comment by fmeringdal** [comment]
There was a DST bug in the library, but I have fixed it now.
So just upgrade the version to 0.5.3 and you shouldnt experience this bug anymore :)
Please feel free to reopen if this issue persist.

**Comment by stevenallen05** [comment]
Awesome, just confirmed and yes - 0.5.3 did fix the issue for DST going in both directions.

You are officially my hero of the week!
